#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from feature_spec_common import (
    derive_feature_title,
    extract_decision_candidates,
    extract_question_lines,
    get_standard_paths,
    list_feedback_candidates,
    merge_source_values,
    next_table_id,
    normalize_text,
    parse_markdown_table,
    read_text_if_exists,
    resolve_feature_dir,
    resolve_repo_root,
    write_text,
)


QUESTION_PLACEHOLDER = {
    "ID": "Q1",
    "Question": "No explicit open questions captured yet.",
    "Status": "Assumption",
    "Blocking": "No",
    "Owner": "TBD",
    "Source": "Generated",
    "Notes": "Add questions during the next review round.",
}

DECISION_PLACEHOLDER = {
    "ID": "D1",
    "Decision / Candidate": "No explicit decisions recorded yet.",
    "Status": "Open",
    "Owner": "TBD",
    "Source": "Generated",
    "Notes": "Capture approved scope decisions between business rounds.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("feature_reference")
    parser.add_argument("--repo-root")
    parser.add_argument("--feature-title")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def is_placeholder_row(row: Dict[str, str], text_key: str, expected_text: str) -> bool:
    return row.get("Source") == "Generated" and row.get(text_key, "").strip() == expected_text


def build_question_document(feature_title: str, rows: Sequence[Dict[str, str]]) -> str:
    lines = [
        f"# Open Questions — {feature_title}",
        "",
        "Last updated: generated by update_question_manager.py",
        "",
        "| ID | Question | Status | Blocking | Owner | Source | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    if rows:
        for row in rows:
            lines.append(
                "| {ID} | {Question} | {Status} | {Blocking} | {Owner} | {Source} | {Notes} |".format(
                    **{key: str(value).replace("|", "\\|") for key, value in row.items()}
                )
            )
    else:
        lines.append(
            "| {ID} | {Question} | {Status} | {Blocking} | {Owner} | {Source} | {Notes} |".format(
                **{key: value.replace("|", "\\|") for key, value in QUESTION_PLACEHOLDER.items()}
            )
        )
    lines.append("")
    return "\n".join(lines)


def build_decision_document(feature_title: str, rows: Sequence[Dict[str, str]]) -> str:
    lines = [
        f"# Decision Log — {feature_title}",
        "",
        "Last updated: generated by update_question_manager.py",
        "",
        "| ID | Decision / Candidate | Status | Owner | Source | Notes |",
        "|---|---|---|---|---|---|",
    ]
    if rows:
        for row in rows:
            escaped = {key: str(value).replace("|", "\\|") for key, value in row.items()}
            lines.append(
                f"| {escaped.get('ID', '')} | {escaped.get('Decision / Candidate', '')} | {escaped.get('Status', '')} | "
                f"{escaped.get('Owner', '')} | {escaped.get('Source', '')} | {escaped.get('Notes', '')} |"
            )
    else:
        escaped = {key: value.replace("|", "\\|") for key, value in DECISION_PLACEHOLDER.items()}
        lines.append(
            f"| {escaped['ID']} | {escaped['Decision / Candidate']} | {escaped['Status']} | {escaped['Owner']} | {escaped['Source']} | {escaped['Notes']} |"
        )
    lines.append("")
    return "\n".join(lines)


def dedupe_discoveries(discovered: Sequence[Tuple[str, str]]) -> List[Tuple[str, str]]:
    merged: Dict[str, Tuple[str, str]] = {}
    for text, source in discovered:
        key = normalize_text(text)
        if not key:
            continue
        if key not in merged:
            merged[key] = (text, source)
            continue
        existing_text, existing_source = merged[key]
        merged[key] = (existing_text, merge_source_values(existing_source, source))
    return list(merged.values())


def collect_questions(feature_dir: Path) -> List[Tuple[str, str]]:
    paths = get_standard_paths(feature_dir)
    discovered: List[Tuple[str, str]] = []
    business_text = read_text_if_exists(paths["business"])
    if business_text:
        for question in extract_question_lines(business_text):
            discovered.append((question, "business.md"))
    for candidate in list_feedback_candidates(feature_dir, include_processed=True):
        feedback_text = read_text_if_exists(Path(candidate["path"]))
        if not feedback_text:
            continue
        for question in extract_question_lines(feedback_text):
            discovered.append((question, candidate["name"]))
    return dedupe_discoveries(discovered)


def collect_decisions(feature_dir: Path) -> List[Tuple[str, str]]:
    paths = get_standard_paths(feature_dir)
    discovered: List[Tuple[str, str]] = []
    business_text = read_text_if_exists(paths["business"])
    if business_text:
        for decision in extract_decision_candidates(business_text):
            discovered.append((decision, "business.md"))
    for candidate in list_feedback_candidates(feature_dir, include_processed=True):
        feedback_text = read_text_if_exists(Path(candidate["path"]))
        if not feedback_text:
            continue
        for decision in extract_decision_candidates(feedback_text):
            discovered.append((decision, candidate["name"]))
    return dedupe_discoveries(discovered)


def merge_questions(existing_rows: Sequence[Dict[str, str]], discovered: Sequence[Tuple[str, str]]) -> List[Dict[str, str]]:
    retained_rows = [
        dict(row)
        for row in existing_rows
        if not is_placeholder_row(row, "Question", QUESTION_PLACEHOLDER["Question"])
    ]
    existing_by_key = {
        normalize_text(row.get("Question", "")): row
        for row in retained_rows
        if row.get("Question")
    }
    ordered_keys = [normalize_text(row.get("Question", "")) for row in retained_rows if row.get("Question")]
    new_rows: List[Dict[str, str]] = []

    for question, source in discovered:
        key = normalize_text(question)
        if not key:
            continue
        if key in existing_by_key:
            row = existing_by_key[key]
            row["Question"] = question
            row["Source"] = merge_source_values(row.get("Source", ""), source)
            if row.get("Status") == "Blocking" and not row.get("Blocking"):
                row["Blocking"] = "Yes"
            if not row.get("Blocking"):
                row["Blocking"] = "Yes" if row.get("Status", "Blocking") == "Blocking" else "No"
            if not row.get("Owner"):
                row["Owner"] = "TBD"
            if not row.get("Notes"):
                row["Notes"] = "Needs business answer or explicit deferral."
            continue

        row = {
            "ID": next_table_id([*retained_rows, *new_rows], "Q"),
            "Question": question,
            "Status": "Blocking",
            "Blocking": "Yes",
            "Owner": "TBD",
            "Source": source,
            "Notes": "Needs business answer or explicit deferral.",
        }
        new_rows.append(row)
        ordered_keys.append(key)
        existing_by_key[key] = row

    merged_rows: List[Dict[str, str]] = []
    seen: set[str] = set()
    for key in ordered_keys:
        if not key or key in seen or key not in existing_by_key:
            continue
        merged_rows.append(existing_by_key[key])
        seen.add(key)
    return merged_rows


def merge_decisions(existing_rows: Sequence[Dict[str, str]], discovered: Sequence[Tuple[str, str]]) -> List[Dict[str, str]]:
    retained_rows = [
        dict(row)
        for row in existing_rows
        if not is_placeholder_row(row, "Decision / Candidate", DECISION_PLACEHOLDER["Decision / Candidate"])
    ]
    existing_by_key = {
        normalize_text(row.get("Decision / Candidate", "")): row
        for row in retained_rows
        if row.get("Decision / Candidate")
    }
    ordered_keys = [normalize_text(row.get("Decision / Candidate", "")) for row in retained_rows if row.get("Decision / Candidate")]
    new_rows: List[Dict[str, str]] = []

    for decision, source in discovered:
        key = normalize_text(decision)
        if not key:
            continue
        if key in existing_by_key:
            row = existing_by_key[key]
            row["Decision / Candidate"] = decision
            row["Source"] = merge_source_values(row.get("Source", ""), source)
            if not row.get("Owner"):
                row["Owner"] = "TBD"
            if not row.get("Notes"):
                row["Notes"] = "Promote to Approved / Deferred / Rejected during review."
            if not row.get("Status"):
                row["Status"] = "Open"
            continue

        row = {
            "ID": next_table_id([*retained_rows, *new_rows], "D"),
            "Decision / Candidate": decision,
            "Status": "Open",
            "Owner": "TBD",
            "Source": source,
            "Notes": "Promote to Approved / Deferred / Rejected during review.",
        }
        new_rows.append(row)
        ordered_keys.append(key)
        existing_by_key[key] = row

    merged_rows: List[Dict[str, str]] = []
    seen: set[str] = set()
    for key in ordered_keys:
        if not key or key in seen or key not in existing_by_key:
            continue
        merged_rows.append(existing_by_key[key])
        seen.add(key)
    return merged_rows


def main() -> int:
    args = parse_args()
    repo_root = resolve_repo_root(args.repo_root)
    feature_dir = resolve_feature_dir(repo_root, args.feature_reference)
    feature_title = derive_feature_title(feature_dir, args.feature_title)
    paths = get_standard_paths(feature_dir)

    question_rows = parse_markdown_table(read_text_if_exists(paths["open_questions"]))
    decision_rows = parse_markdown_table(read_text_if_exists(paths["decision_log"]))
    discovered_questions = collect_questions(feature_dir)
    discovered_decisions = collect_decisions(feature_dir)

    merged_questions = merge_questions(question_rows, discovered_questions)
    merged_decisions = merge_decisions(decision_rows, discovered_decisions)

    question_doc = build_question_document(feature_title, merged_questions)
    decision_doc = build_decision_document(feature_title, merged_decisions)

    if args.write:
        write_text(paths["open_questions"], question_doc)
        write_text(paths["decision_log"], decision_doc)

    payload = {
        "featureDir": str(feature_dir),
        "featureTitle": feature_title,
        "openQuestionsPath": str(paths["open_questions"]),
        "decisionLogPath": str(paths["decision_log"]),
        "questionCount": len(merged_questions),
        "decisionCount": len(merged_decisions),
        "newQuestionCount": max(len(merged_questions) - len([row for row in question_rows if not is_placeholder_row(row, "Question", QUESTION_PLACEHOLDER["Question"])]), 0),
        "newDecisionCount": max(len(merged_decisions) - len([row for row in decision_rows if not is_placeholder_row(row, "Decision / Candidate", DECISION_PLACEHOLDER["Decision / Candidate"])]), 0),
    }
    if args.json:
        print(json.dumps(payload, indent=2, ensure_ascii=False))
    else:
        print(f"Open questions: {payload['questionCount']} -> {payload['openQuestionsPath']}")
        print(f"Decision candidates: {payload['decisionCount']} -> {payload['decisionLogPath']}")
        if args.write:
            print("Updated open-questions.md and decision-log.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
